[theme]
base = "light"
primaryColor = "#0056B3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF4FB"
textColor = "#102035"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
